name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          build: yarn build
          start: yarn test:ci
          record: false
        env:
          NODE_ENV: test
          RUNNING_TEST: true
          REACT_APP_ENV: test
          NEXT_PUBLIC_BASE_URL: http://localhost:4200
          NEXT_PUBLIC_APP_LOCALE: pt-br
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: secret
